-- MySQL Script generated by MySQL Workbench
-- Mon Mar  5 16:03:10 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `Build`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Build` (
  `idBuild` INT(11) NOT NULL AUTO_INCREMENT,
  `major` INT(11) NOT NULL COMMENT 'Year of this build.',
  `minor` INT(11) NOT NULL COMMENT 'Week within the Sprint',
  `patch` INT(11) NOT NULL COMMENT 'Sequential build number of this build',
  `firstTested` DATETIME NOT NULL COMMENT 'Date time value for the very first test run against this build. ',
  `lastTested` DATETIME NOT NULL COMMENT 'Date time value of the most recent test run against this build. ',
  PRIMARY KEY (`idBuild`),
  UNIQUE INDEX `buildNumber` (`major` ASC, `minor` ASC, `patch` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `MeasurementName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MeasurementName` (
  `idMeasurementName` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idMeasurementName`),
  UNIQUE INDEX `measurementName_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestDefinition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestDefinition` (
  `idTestDefinition` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Auto Incrementing key for Description table.',
  `methodSignature` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `active` TINYINT(1) NOT NULL,
  `productName` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `subProductName` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `className` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `methodName` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  `documentation` TEXT CHARACTER SET 'latin1' NULL DEFAULT NULL COMMENT 'This field is reserved for documentation (if any) about the test. It may be null. ',
  PRIMARY KEY (`idTestDefinition`),
  UNIQUE INDEX `methodSignature` (`methodSignature` ASC),
  INDEX `reportingDescription` (`productName` ASC, `subProductName` ASC, `className` ASC, `methodName` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestExecution`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestExecution` (
  `idTestExecution` INT(11) NOT NULL AUTO_INCREMENT,
  `idTestDefinition` INT(11) NOT NULL,
  `idBuild` INT(11) NOT NULL,
  `passed` TINYINT(1) NOT NULL,
  `responseTime` DOUBLE NOT NULL,
  `responseTimeRequirement` DOUBLE NOT NULL,
  `startTime` DATETIME NOT NULL,
  `endTime` DATETIME NOT NULL,
  PRIMARY KEY (`idTestExecution`),
  INDEX `description_idx` (`idTestDefinition` ASC),
  INDEX `buildinfo_idx` (`idBuild` ASC),
  CONSTRAINT `definition_TestExecution`
    FOREIGN KEY (`idTestDefinition`)
    REFERENCES `TestDefinition` (`idTestDefinition`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idBuild`
    FOREIGN KEY (`idBuild`)
    REFERENCES `Build` (`idBuild`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Measurement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Measurement` (
  `idTestExecution` INT(11) NOT NULL COMMENT 'Foreign key pointing to the test execution.',
  `idMeasurementName` INT(11) NOT NULL COMMENT 'Foreign key pointing to the description.',
  `result` DOUBLE NOT NULL COMMENT 'Result of a given measurement. Kept as a DOUBLE to allow for the greatest range of possible values for this field. ',
  PRIMARY KEY (`idTestExecution`, `idMeasurementName`),
  INDEX `idTestExecution_idx` (`idTestExecution` ASC),
  INDEX `idName_idx` (`idMeasurementName` ASC),
  CONSTRAINT `idMeasurementDescription`
    FOREIGN KEY (`idMeasurementName`)
    REFERENCES `MeasurementName` (`idMeasurementName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTestExecution_Measurement`
    FOREIGN KEY (`idTestExecution`)
    REFERENCES `TestExecution` (`idTestExecution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TagName`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TagName` (
  `idTagName` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `nameType` VARCHAR(255) NOT NULL DEFAULT 'plain_txt' COMMENT 'Use Case for the Description. (i.e href, text, .etc) defaults to plain_txt.',
  `isUserGenerated` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Indicates whether or nor the tag is user submitted',
  PRIMARY KEY (`idTagName`),
  UNIQUE INDEX `tagName_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestDefinitionTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestDefinitionTag` (
  `idTestDefinitionTag` INT(11) NOT NULL AUTO_INCREMENT,
  `idTestDefinition` INT(11) NOT NULL COMMENT 'Foreign key pointing to the test definition.',
  `idTagName` INT(11) NOT NULL COMMENT 'Foreign key pointing to the tag description.',
  `value` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL COMMENT 'Value of a given tag.',
  PRIMARY KEY (`idTestDefinitionTag`),
  UNIQUE INDEX `idTestDefinition_value_TagName_unique` (`value` ASC, `idTagName` ASC, `idTestDefinition` ASC),
  INDEX `idTestDefinition_idx` (`idTestDefinition` ASC),
  INDEX `idTagName_idx` (`idTagName` ASC),
  CONSTRAINT `idTagDescription_TestDefinitionTag`
    FOREIGN KEY (`idTagName`)
    REFERENCES `TagName` (`idTagName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTestDefinition_Tag`
    FOREIGN KEY (`idTestDefinition`)
    REFERENCES `TestDefinition` (`idTestDefinition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestDefinitionMetaTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestDefinitionMetaTag` (
  `idTestDefinitionTag` INT(11) NOT NULL,
  `idTagName` INT(11) NOT NULL,
  `value` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idTestDefinitionTag`, `idTagName`),
  INDEX `idTagName_DefinitionMetaTag_idx` (`idTagName` ASC),
  CONSTRAINT `idTagName_DefinitionMetaTag`
    FOREIGN KEY (`idTagName`)
    REFERENCES `TagName` (`idTagName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTestDefinitionTag_DefinitionMetaTag`
    FOREIGN KEY (`idTestDefinitionTag`)
    REFERENCES `TestDefinitionTag` (`idTestDefinitionTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestExecutionTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestExecutionTag` (
  `idTestExecutionTag` INT(11) NOT NULL AUTO_INCREMENT,
  `idTestExecution` INT(11) NOT NULL COMMENT 'Foreign key pointing to the test execution.',
  `idTagName` INT(11) NOT NULL COMMENT 'Foreign key pointing to the tag description.',
  `value` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL COMMENT 'Value of a given tag. ',
  PRIMARY KEY (`idTestExecutionTag`),
  UNIQUE INDEX `idTestExecution_value_TagName_unique` (`value` ASC, `idTagName` ASC, `idTestExecution` ASC),
  INDEX `idTestExecution_idx` (`idTestExecution` ASC),
  INDEX `idTagName_idx` (`idTagName` ASC),
  CONSTRAINT `idTagName_TestExecutionTag`
    FOREIGN KEY (`idTagName`)
    REFERENCES `TagName` (`idTagName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTestExecution_Tag`
    FOREIGN KEY (`idTestExecution`)
    REFERENCES `TestExecution` (`idTestExecution`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TestExecutionMetaTag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TestExecutionMetaTag` (
  `idTestExecutionTag` INT(11) NOT NULL,
  `idTagName` INT(11) NOT NULL,
  `value` VARCHAR(255) CHARACTER SET 'latin1' NOT NULL,
  PRIMARY KEY (`idTestExecutionTag`, `idTagName`),
  INDEX `idTagName_ExecutionMetaTag_idx` (`idTagName` ASC),
  CONSTRAINT `idTagName_ExecutionMetaTag`
    FOREIGN KEY (`idTagName`)
    REFERENCES `TagName` (`idTagName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idTestExecutionTag_ExecutionMetaTag`
    FOREIGN KEY (`idTestExecutionTag`)
    REFERENCES `TestExecutionTag` (`idTestExecutionTag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
