name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      mysql:
        image: mysql:5.7.24
        ports:
          - 3307:3306
        env:
          # make sure to use something more secure in production
          MYSQL_ROOT_PASSWORD: 1234
          MYSQL_DATABASE: warp_core
      influxdb:
        image: influxdb:1.5.2
        ports:
          - 8086:8086

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile
        run: ./gradlew clean compileTestScala

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew copyConfigTemplate test
